apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: tesify-ingress-route
  labels:
    app: backend
  annotations:
    secret.reloader.stakater.com/reload: "backend-secret"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shivamsharma0309/cafeasebackend:v1   # docker image
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: secret-volume
              mountPath: /app/config/.env      # where your app expects it env
              subPath: .env
          resources:                           # ✅ moved under container
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: secret-volume
          secret:
            secretName: backend-secret
